name: Run Pytest

on:
  push:
    branches:
      - main  # This means the workflow will run when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # This means the workflow will run when a pull request is made targeting 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # This means the workflow will run on an Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action will checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # This action will set up Python in the environment
      with:
        python-version: '3.8'  # You can specify any version of Python here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # This installs dependencies from your 'requirements.txt'

    - name: Run tests with pytest
      run: |
        pytest -v tests/  # The -v flag gives verbose output and shows more details for each test case

    - name: Upload pytest results (Optional)
      if: failure()  # This step runs only if the tests fail
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: test-results.xml  # Path to your pytest results (if generated)
